[package]
name = "rev"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
serde_json = "1.0.140"
static_init = "1.0.3"
thiserror = "2.0.12"
tungstenite = "0.27.0"
url = "2.5.4"
